version: 1
formatters:
  onlyMessage:
    format: "%(message)s"
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class : logging.StreamHandler
    formatter: onlyMessage
    level   : INFO
    stream  : ext://sys.stdout
  debug_main_scheduler:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_main_scheduler.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  debug_listSpider:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_listSpider.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  debug_postSpider:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_postSpider.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  debug_replySpider:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_replySpider.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  debug_userSpider:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_userSpider.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  debug_statusCodeMiddleware:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/debug_statusCodeMiddleware.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  main:
    level: DEBUG
    handlers: [console]
  main.scheduler:
    level: DEBUG
    handlers: [debug_main_scheduler]
  main.debug_listSpider:
    level: DEBUG
    handlers: [debug_listSpider]
  main.debug_postSpider:
    level: DEBUG
    handlers: [debug_postSpider]
  main.debug_replySpider:
    level: DEBUG
    handlers: [debug_replySpider]
  main.debug_userSpider:
    level: DEBUG
    handlers: [debug_userSpider]
  main.statusCodeMiddleware:
    level: DEBUG
    handlers: [debug_statusCodeMiddleware]
  main.error:
    level: DEBUG
    handlers: [error]
root:
  level: WARN
  handlers: []